services:
  backend:
    container_name: flex-it-proj-backend
    build:
      context: ./backend
      dockerfile: Dockerfile-dev
    environment:
      - API_PREFIX=/api/v1/
      - DB_TYPE=postgres
      - DB_HOST=172.18.0.2
      - DB_NAME=flex-it-database
      - DB_USER=node 
      - DB_PASS=node
      - DB_PORT=5432
      - NODE_ENV=development
      - PORT=8030
    ports:
      - "8030:8030"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    networks:
      - flex-it-dev

networks:
  flex-it-dev:
    external: true