services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: flex-it-database
    networks:
      - flex-it-dev
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - flex-it-dev
  pgAdmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: flexit@flexit.com
      PGADMIN_DEFAULT_PASSWORD: flexit
    networks:
      - flex-it-dev

networks:
  flex-it-dev:
    external: true